//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simir.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simir.Domain.MensagensErro", typeof(MensagensErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar ao menos uma atividade da empresa referente ao RSU..
        /// </summary>
        public static string atividadesEmpresa {
            get {
                return ResourceManager.GetString("atividadesEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione ao menos uma licença operacional..
        /// </summary>
        public static string avisoLicencaVazia {
            get {
                return ResourceManager.GetString("avisoLicencaVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Bairro não corresponde à Cidade..
        /// </summary>
        public static string bairroCidadeDiferente {
            get {
                return ResourceManager.GetString("bairroCidadeDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este bairro não existe em nossa base de dados..
        /// </summary>
        public static string bairroInexistente {
            get {
                return ResourceManager.GetString("bairroInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Bairro não corresponde ao CEP..
        /// </summary>
        public static string cepBairroDiferente {
            get {
                return ResourceManager.GetString("cepBairroDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cidade não corresponde ao CEP..
        /// </summary>
        public static string cepCidadeDiferente {
            get {
                return ResourceManager.GetString("cepCidadeDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Estado não corresponde ao CEP..
        /// </summary>
        public static string cepEstadoDiferente {
            get {
                return ResourceManager.GetString("cepEstadoDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP não encontrado. Preencha os campos manualmente..
        /// </summary>
        public static string cepInexistente {
            get {
                return ResourceManager.GetString("cepInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP inválido..
        /// </summary>
        public static string cepInvalido {
            get {
                return ResourceManager.GetString("cepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cidade não corresponde ao Estado..
        /// </summary>
        public static string cidadeEstadoDiferente {
            get {
                return ResourceManager.GetString("cidadeEstadoDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ não encontrado. Preencha os campos manualmente..
        /// </summary>
        public static string cnpjInexistente {
            get {
                return ResourceManager.GetString("cnpjInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnpj inválido..
        /// </summary>
        public static string cnpjInvalido {
            get {
                return ResourceManager.GetString("cnpjInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ já foi cadastrado..
        /// </summary>
        public static string cnpjJaCadastrado {
            get {
                return ResourceManager.GetString("cnpjJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de encerramento não pode ser menor que a data de Início..
        /// </summary>
        public static string DataEncerramentoMenor {
            get {
                return ResourceManager.GetString("DataEncerramentoMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato de data inválida.
        /// </summary>
        public static string dataInvalida {
            get {
                return ResourceManager.GetString("dataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não pode ser menor que o dia atual..
        /// </summary>
        public static string DataMenorAtual {
            get {
                return ResourceManager.GetString("DataMenorAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta data está vencida.
        /// </summary>
        public static string dataVencida {
            get {
                return ResourceManager.GetString("dataVencida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já foi cadastrado..
        /// </summary>
        public static string emailJaCadastrado {
            get {
                return ResourceManager.GetString("emailJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não possui altorização para alterar esta empresa.
        /// </summary>
        public static string empresaIDIncompativel {
            get {
                return ResourceManager.GetString("empresaIDIncompativel", resourceCulture);
            }
        }
    }
}
